name: Publish changelog pages

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build pages
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: |
          pip install markdown
          python3 tools/generate-html-pages.py

      - name: upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: changelog-html/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
